#pragma once
#include "AE_Effect.h"
#include "AE_EffectUI.h"
#include "ProfileData.h"

enum ParamIndex {
 SOURCE_INPUT, SOURCE_MATTE, MATTE_CHANNEL,
 PATH, AMOUNT, RADIUS, FEATHER, STREAK, FREQUENCY, ORIGINAL, REVERSE, SEED, PREVIEW,
 END_CAP, SAMPLING,
 PROFILE_GROUP, PROFILE, PROFILE_SMOOTH, PROFILE_RESET, PROFILE_FLIP, PROFILE_DELETE, PROFILE_GROUP_END,
 LEGACY_INVERT_MATTE,
 COUNT
};
// These IDs are written into AEP files. Keep them stable even when the UI order changes.
enum ParamDiskID {
 DISK_PATH=1, DISK_AMOUNT=2, DISK_RADIUS=3, DISK_FEATHER=4, DISK_STREAK=5,
 DISK_FREQUENCY=6, DISK_ORIGINAL=7, DISK_REVERSE=8, DISK_SEED=9, DISK_PREVIEW=10,
 DISK_END_CAP=11, DISK_SAMPLING=12, DISK_PROFILE=13, DISK_PROFILE_SMOOTH=14,
 DISK_PROFILE_RESET=15, DISK_PROFILE_FLIP=16, DISK_PROFILE_DELETE=17,
 DISK_SOURCE_MATTE=18, DISK_MATTE_CHANNEL=19, DISK_LEGACY_INVERT_MATTE=20,
 DISK_PROFILE_GROUP=21, DISK_PROFILE_GROUP_END=22
};
constexpr int PROFILE_UI_WIDTH=240,PROFILE_UI_HEIGHT=159;
inline void* const PROFILE_REFCON=reinterpret_cast<void*>(static_cast<std::uintptr_t>(0x43535031));

PF_Err CreateDefaultProfile(PF_InData*,PF_ArbitraryH*);
PF_Err HandleArbitrary(PF_InData*,PF_OutData*,PF_ArbParamsExtra*);
PF_Err HandleProfileEvent(PF_InData*,PF_OutData*,PF_ParamDef*[],PF_EventExtra*);
PF_Err HandleProfileButton(PF_InData*,PF_OutData*,PF_ParamDef*[],PF_UserChangedParamExtra*);
